pipeline{
    agent any
    stages{
        stage("checkout"){
            steps{
                git "https://github.com/ashu847/tour-management-system.git"
            }
        }
        
         stage("package"){
            steps{
            sh "mvn clean package"
            }
        }
    }
 }