server:
  port: 8880

spring:
  application:
   name: tour-management-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWOED:root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/tour}
    username: ${DB_USER:root}
  jpa:
    show-sql: true


eureka:
  client:
   register-with-eureka: true
   service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
      

      
     